export const validUser = {
  username: 'admin',
  password: 'admin'
};

export const invalidUser = {
  username: 'wronguser',
  password: 'badpass'
};

export const newItem = () => ({
  title: `Test item ${Date.now()}`,
  description: 'autogenerated description'
});
