# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      runtime:
        description: "Node version"
        required: false
        default: "20"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run docker‑compose tests
        run: |
          docker-compose -f docker-compose.yml up --build --abort-on-container-exit tests
